orbs:
  node: circleci/node@5.0.2
version: 2.1

workflows:
  test-matrix:
    jobs:
      - node/test:
          name: node-16
          version: 16.10.0
          pkg-manager: yarn
      - node/test:
          name: node-14
          version: 14.15.0
          pkg-manager: yarn
